name: Trigger auto deployment for aca-az2003

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aca-az2003-AutoDeployTrigger-7541d359-7b60-4d76-b574-9e33163cb87c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACAAZ2003_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACAAZ2003_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACAAZ2003_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: acraz2003klp20may.azurecr.io
          registryUsername: ${{ secrets.ACAAZ2003_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAAZ2003_REGISTRY_PASSWORD }}
          containerAppName: aca-az2003
          resourceGroup: monkeydust-sandbox-rg
          imageToBuild: acraz2003klp20may.azurecr.io/aca-az2003:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


